#!/usr/bin/env python3
"""
    This script handles installing system dependencies for games using the
    Steam runtime.  It is intended to be customized by other distributions
    to "do the right thing"

    Usage: steamdeps dependencies.txt
"""

import argparse
import glob
import logging
import os
import re
import shlex
import shutil
import subprocess
import sys

check_output = subprocess.run(["dpkg -s libc6:amd64 && dpkg -s libc6:i386"], shell=True)
if (check_output.returncode) != 0:
    subprocess.run(["/usr/bin/x-terminal-emulator -e bash -c 'sudo apt install -y libc6:amd64 libc6:i386'"], shell=True)
    exit(0)
else
    exit(0)